/**
 * Card Seed Data
 * 120 balanced cards (40 per faction) for TCG Tactique
 */
import { Card, CardAbility } from '../src/types/database';

// Helper function to create card abilities
const ability = (id: string, name: string, description: string, effectType: 'passive' | 'triggered' | 'activated', parameters: Record<string, any> = {}): CardAbility => ({
  id,
  name,
  description,
  effectType,
  parameters
});

// Common abilities (referenced in cards)
const ABILITIES = {
  armor: ability('armor', 'Armor Plating', 'Takes 1 less damage from attacks (minimum 1)', 'passive', { damageReduction: 1 }),
  firstStrike: ability('first_strike', 'First Strike', 'Attacks first in combat', 'passive'),
  regeneration: ability('regeneration', 'Regeneration', 'Heals 1 HP at the start of each turn', 'triggered', { healAmount: 1 }),
  swarm: ability('swarm', 'Swarm', '+1 attack for each adjacent alien unit', 'passive', { attackBonus: 1 }),
  leadership: ability('leadership', 'Leadership', 'Adjacent human units gain +1 attack', 'passive', { attackBonus: 1 }),
  selfRepair: ability('self_repair', 'Self-Repair', 'Heals 2 HP when played', 'triggered', { healAmount: 2 }),
  charge: ability('charge', 'Charge', 'Can attack immediately when played', 'triggered'),
  stealth: ability('stealth', 'Stealth', 'Cannot be targeted by attacks for 1 turn', 'triggered'),
  explosive: ability('explosive', 'Explosive', 'Deals 2 damage to adjacent units when destroyed', 'triggered'),
  sniper: ability('sniper_scope', 'Sniper Scope', 'Can attack any unit on the battlefield', 'passive')
};

// Human Cards (40) - Discipline/Coordination theme
export const HUMAN_CARDS: Omit<Card, 'id' | 'createdAt' | 'updatedAt'>[] = [
  // Cost 1 Units (6 cards)
  {
    name: 'Rookie Marine',
    faction: 'humans',
    type: 'unit',
    cost: 1,
    attack: 1,
    hp: 2,
    range: 1,
    abilities: [],
    description: 'Basic human infantry unit with balanced stats',
    flavorText: 'Every legend starts somewhere.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Scout',
    faction: 'humans',
    type: 'unit',
    cost: 1,
    attack: 2,
    hp: 1,
    range: 2,
    abilities: [],
    description: 'Fast, fragile unit with extended range',
    flavorText: 'Eyes and ears of the squad.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Medic',
    faction: 'humans',
    type: 'unit',
    cost: 1,
    attack: 0,
    hp: 3,
    range: 1,
    abilities: [ABILITIES.regeneration],
    description: 'Support unit that provides healing',
    flavorText: 'First to help, last to fall.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Communications Officer',
    faction: 'humans',
    type: 'unit',
    cost: 1,
    attack: 1,
    hp: 1,
    range: 1,
    abilities: [ABILITIES.leadership],
    description: 'Provides tactical coordination',
    flavorText: 'Unity through communication.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Engineer',
    faction: 'humans',
    type: 'unit',
    cost: 1,
    attack: 1,
    hp: 2,
    range: 1,
    abilities: [ability('repair', 'Repair', 'Adjacent humans heal 1 HP at turn start', 'triggered')],
    description: 'Technical support specialist',
    flavorText: 'Building tomorrow today.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Tactical Drone',
    faction: 'humans',
    type: 'unit',
    cost: 1,
    attack: 1,
    hp: 1,
    range: 2,
    abilities: [ABILITIES.stealth],
    description: 'Automated reconnaissance unit',
    flavorText: 'Silent. Deadly. Efficient.',
    setId: 'alpha-1',
    isActive: true
  },

  // Cost 2 Units (8 cards)
  {
    name: 'Tactical Squad',
    faction: 'humans',
    type: 'unit',
    cost: 2,
    attack: 2,
    hp: 3,
    range: 1,
    abilities: [],
    description: 'Standard human infantry squad',
    flavorText: 'Discipline forged in fire.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Assault Trooper',
    faction: 'humans',
    type: 'unit',
    cost: 2,
    attack: 3,
    hp: 2,
    range: 1,
    abilities: [ABILITIES.charge],
    description: 'Aggressive front-line fighter',
    flavorText: 'First in, last out.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Marksman',
    faction: 'humans',
    type: 'unit',
    cost: 2,
    attack: 2,
    hp: 2,
    range: 3,
    abilities: [],
    description: 'Long-range precision shooter',
    flavorText: 'One shot, one kill.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Heavy Gunner',
    faction: 'humans',
    type: 'unit',
    cost: 2,
    attack: 1,
    hp: 4,
    range: 2,
    abilities: [ability('suppression', 'Suppression', 'Attacked units cannot attack next turn', 'triggered')],
    description: 'Defensive specialist with heavy weapons',
    flavorText: 'Hold the line.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Squad Leader',
    faction: 'humans',
    type: 'unit',
    cost: 2,
    attack: 2,
    hp: 2,
    range: 1,
    abilities: [ABILITIES.leadership],
    description: 'Commands nearby units effectively',
    flavorText: 'Lead by example.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Combat Engineer',
    faction: 'humans',
    type: 'unit',
    cost: 2,
    attack: 1,
    hp: 3,
    range: 1,
    abilities: [ability('fortify', 'Fortify', 'Adjacent humans gain +0/+1', 'passive')],
    description: 'Builds defensive positions',
    flavorText: 'Prepare for anything.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Cyber Specialist',
    faction: 'humans',
    type: 'unit',
    cost: 2,
    attack: 2,
    hp: 1,
    range: 2,
    abilities: [ability('hack', 'Hack', 'Disable enemy abilities for 1 turn', 'activated')],
    description: 'Electronic warfare expert',
    flavorText: 'Fighting in cyberspace.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Grenadier',
    faction: 'humans',
    type: 'unit',
    cost: 2,
    attack: 2,
    hp: 2,
    range: 2,
    abilities: [ABILITIES.explosive],
    description: 'Explosives expert',
    flavorText: 'Sometimes you need a bigger boom.',
    setId: 'alpha-1',
    isActive: true
  },

  // Cost 3 Units (8 cards)
  {
    name: 'Elite Marine',
    faction: 'humans',
    type: 'unit',
    cost: 3,
    attack: 3,
    hp: 3,
    range: 1,
    abilities: [ABILITIES.firstStrike],
    description: 'Veteran soldier with superior training',
    flavorText: 'Excellence through experience.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Sniper',
    faction: 'humans',
    type: 'unit',
    cost: 3,
    attack: 3,
    hp: 1,
    range: 3,
    abilities: [ABILITIES.sniper],
    description: 'Long-range assassin',
    flavorText: 'Patience. Precision. Victory.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Command Sergeant',
    faction: 'humans',
    type: 'unit',
    cost: 3,
    attack: 2,
    hp: 3,
    range: 1,
    abilities: [ABILITIES.leadership, ability('rally', 'Rally', 'All humans gain +1/+0 this turn', 'activated')],
    description: 'Senior NCO who inspires troops',
    flavorText: 'Follow me!',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Heavy Weapons Team',
    faction: 'humans',
    type: 'unit',
    cost: 3,
    attack: 4,
    hp: 2,
    range: 3,
    abilities: [ability('setup', 'Setup Required', 'Cannot attack the turn played', 'passive')],
    description: 'Devastating firepower with setup time',
    flavorText: 'Overwhelming force.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Commando',
    faction: 'humans',
    type: 'unit',
    cost: 3,
    attack: 3,
    hp: 2,
    range: 1,
    abilities: [ABILITIES.stealth, ABILITIES.firstStrike],
    description: 'Elite special operations soldier',
    flavorText: 'Behind enemy lines.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Field Medic',
    faction: 'humans',
    type: 'unit',
    cost: 3,
    attack: 1,
    hp: 4,
    range: 1,
    abilities: [ability('field_medicine', 'Field Medicine', 'Heal target human for 3 HP', 'activated')],
    description: 'Advanced medical support',
    flavorText: 'No one left behind.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Tank Commander',
    faction: 'humans',
    type: 'unit',
    cost: 3,
    attack: 2,
    hp: 4,
    range: 2,
    abilities: [ABILITIES.armor],
    description: 'Armored vehicle crew leader',
    flavorText: 'Steel and determination.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Air Support Coordinator',
    faction: 'humans',
    type: 'unit',
    cost: 3,
    attack: 1,
    hp: 3,
    range: 1,
    abilities: [ability('air_strike', 'Air Strike', 'Deal 2 damage to any target', 'activated')],
    description: 'Calls in aerial bombardment',
    flavorText: 'Danger close.',
    setId: 'alpha-1',
    isActive: true
  },

  // Cost 4-5 Units (12 cards)
  {
    name: 'Captain',
    faction: 'humans',
    type: 'unit',
    cost: 4,
    attack: 3,
    hp: 4,
    range: 1,
    abilities: [ABILITIES.leadership, ability('inspire', 'Inspire', 'All humans gain +1/+1 when played', 'triggered')],
    description: 'Company commander who boosts morale',
    flavorText: 'Victory through leadership.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Assault Mech',
    faction: 'humans',
    type: 'unit',
    cost: 4,
    attack: 4,
    hp: 3,
    range: 1,
    abilities: [ABILITIES.armor],
    description: 'Powered armor assault unit',
    flavorText: 'Technology meets courage.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Artillery Specialist',
    faction: 'humans',
    type: 'unit',
    cost: 4,
    attack: 5,
    hp: 2,
    range: 3,
    abilities: [ability('artillery', 'Artillery', 'Deal 1 damage to adjacent enemies when attacking', 'triggered')],
    description: 'Long-range bombardment expert',
    flavorText: 'Rain of destruction.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Special Forces Commander',
    faction: 'humans',
    type: 'unit',
    cost: 4,
    attack: 3,
    hp: 3,
    range: 2,
    abilities: [ABILITIES.firstStrike, ABILITIES.leadership],
    description: 'Elite tactical leader',
    flavorText: 'Elite leading elite.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Heavy Tank',
    faction: 'humans',
    type: 'unit',
    cost: 5,
    attack: 4,
    hp: 5,
    range: 2,
    abilities: [ABILITIES.armor],
    description: 'Main battle tank',
    flavorText: 'Unstoppable force.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Major',
    faction: 'humans',
    type: 'unit',
    cost: 5,
    attack: 4,
    hp: 4,
    range: 1,
    abilities: [ABILITIES.leadership, ability('tactical_supremacy', 'Tactical Supremacy', 'Humans can attack twice per turn', 'passive')],
    description: 'Senior tactical commander',
    flavorText: 'Strategy incarnate.',
    setId: 'alpha-1',
    isActive: true
  },

  // Cost 6+ Legendary Units (6 cards)
  {
    name: 'General',
    faction: 'humans',
    type: 'unit',
    cost: 6,
    attack: 5,
    hp: 5,
    range: 1,
    abilities: [
      ABILITIES.leadership,
      ability('supreme_command', 'Supreme Command', 'All humans gain +2/+2 and First Strike', 'passive')
    ],
    description: 'Supreme battlefield commander',
    flavorText: 'Victory through superior leadership.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Orbital Strike Commander',
    faction: 'humans',
    type: 'unit',
    cost: 7,
    attack: 6,
    hp: 4,
    range: 3,
    abilities: [ability('orbital_strike', 'Orbital Strike', 'Deal 4 damage to any target', 'activated')],
    description: 'Commands devastating orbital weapons',
    flavorText: 'From the heavens comes judgment.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Fortress Commander',
    faction: 'humans',
    type: 'unit',
    cost: 8,
    attack: 4,
    hp: 8,
    range: 2,
    abilities: [ABILITIES.armor, ability('fortress', 'Mobile Fortress', 'Adjacent humans cannot be attacked', 'passive')],
    description: 'Unbreakable defensive specialist',
    flavorText: 'An immovable object.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Supreme Commander',
    faction: 'humans',
    type: 'unit',
    cost: 10,
    attack: 7,
    hp: 7,
    range: 2,
    abilities: [
      ABILITIES.leadership,
      ability('total_war', 'Total War', 'All humans can attack twice per turn', 'passive')
    ],
    description: 'Ultimate human commander',
    flavorText: 'The apex of human military doctrine.',
    setId: 'alpha-1',
    isActive: true
  }
];

// Alien Cards (40) - Evolution/Adaptation theme
export const ALIEN_CARDS: Omit<Card, 'id' | 'createdAt' | 'updatedAt'>[] = [
  // Cost 1 Units (6 cards)
  {
    name: 'Hive Drone',
    faction: 'aliens',
    type: 'unit',
    cost: 1,
    attack: 1,
    hp: 1,
    range: 1,
    abilities: [ABILITIES.swarm],
    description: 'Basic swarm unit that grows stronger together',
    flavorText: 'Strength in numbers.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Spore Crawler',
    faction: 'aliens',
    type: 'unit',
    cost: 1,
    attack: 2,
    hp: 1,
    range: 1,
    abilities: [ability('spores', 'Toxic Spores', 'Attackers take 1 damage', 'triggered')],
    description: 'Defensive organism with toxic capabilities',
    flavorText: 'Death breeds death.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Scout Larva',
    faction: 'aliens',
    type: 'unit',
    cost: 1,
    attack: 1,
    hp: 2,
    range: 1,
    abilities: [ability('metamorphosis', 'Metamorphosis', 'Becomes a 2/3 after 1 turn', 'triggered')],
    description: 'Juvenile form that evolves rapidly',
    flavorText: 'Growth is inevitable.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Feeder',
    faction: 'aliens',
    type: 'unit',
    cost: 1,
    attack: 0,
    hp: 3,
    range: 1,
    abilities: [ability('consume', 'Consume', 'Gain +1/+0 when any unit dies', 'triggered')],
    description: 'Scavenger that grows from death',
    flavorText: 'Nothing goes to waste.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Symbiote',
    faction: 'aliens',
    type: 'unit',
    cost: 1,
    attack: 1,
    hp: 1,
    range: 1,
    abilities: [ability('bond', 'Symbiotic Bond', 'Adjacent aliens gain +0/+1', 'passive')],
    description: 'Supportive organism that strengthens others',
    flavorText: 'Together we thrive.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Acid Spitter',
    faction: 'aliens',
    type: 'unit',
    cost: 1,
    attack: 1,
    hp: 1,
    range: 2,
    abilities: [ability('corrosive', 'Corrosive', 'Attacked units lose 1 armor', 'triggered')],
    description: 'Ranged attacker with armor penetration',
    flavorText: 'Melting through defenses.',
    setId: 'alpha-1',
    isActive: true
  },

  // Cost 2 Units (8 cards)
  {
    name: 'Warrior Drone',
    faction: 'aliens',
    type: 'unit',
    cost: 2,
    attack: 2,
    hp: 2,
    range: 1,
    abilities: [ABILITIES.swarm],
    description: 'Combat-evolved drone with pack tactics',
    flavorText: 'Evolved for war.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Hunter',
    faction: 'aliens',
    type: 'unit',
    cost: 2,
    attack: 3,
    hp: 1,
    range: 1,
    abilities: [ability('pounce', 'Pounce', 'Can attack units with higher cost', 'passive')],
    description: 'Specialized predator',
    flavorText: 'Born to hunt.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Regenerator',
    faction: 'aliens',
    type: 'unit',
    cost: 2,
    attack: 1,
    hp: 3,
    range: 1,
    abilities: [ABILITIES.regeneration],
    description: 'Rapidly healing organism',
    flavorText: 'Wounds only make us stronger.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Spawner',
    faction: 'aliens',
    type: 'unit',
    cost: 2,
    attack: 1,
    hp: 2,
    range: 1,
    abilities: [ability('spawn', 'Spawn', 'Create a 1/1 drone when played', 'triggered')],
    description: 'Produces additional organisms',
    flavorText: 'Life finds a way.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Adaptation Chamber',
    faction: 'aliens',
    type: 'unit',
    cost: 2,
    attack: 0,
    hp: 4,
    range: 1,
    abilities: [ability('adapt', 'Adaptation', 'Aliens gain +1/+0 when entering play', 'passive')],
    description: 'Evolution accelerator',
    flavorText: 'Change is the only constant.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Venomous Striker',
    faction: 'aliens',
    type: 'unit',
    cost: 2,
    attack: 2,
    hp: 1,
    range: 1,
    abilities: [ability('venom', 'Venom', 'Attacked units lose 1 HP per turn', 'triggered')],
    description: 'Poison-based attacker',
    flavorText: 'Death by a thousand cuts.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Carapace Warrior',
    faction: 'aliens',
    type: 'unit',
    cost: 2,
    attack: 1,
    hp: 3,
    range: 1,
    abilities: [ability('shell', 'Hardened Carapace', 'Takes 1 less damage from ranged attacks', 'passive')],
    description: 'Armored alien with natural protection',
    flavorText: 'Evolution\'s armor.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Hive Mind Node',
    faction: 'aliens',
    type: 'unit',
    cost: 2,
    attack: 0,
    hp: 3,
    range: 1,
    abilities: [ability('hive_link', 'Hive Link', 'All aliens gain +0/+1', 'passive')],
    description: 'Collective consciousness booster',
    flavorText: 'We are one.',
    setId: 'alpha-1',
    isActive: true
  },

  // Cost 3 Units (8 cards)
  {
    name: 'Apex Predator',
    faction: 'aliens',
    type: 'unit',
    cost: 3,
    attack: 4,
    hp: 2,
    range: 1,
    abilities: [ability('hunt', 'Hunt', 'Gains +1/+1 for each enemy killed', 'triggered')],
    description: 'Ultimate evolutionary hunter',
    flavorText: 'Top of the food chain.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Broodmother',
    faction: 'aliens',
    type: 'unit',
    cost: 3,
    attack: 1,
    hp: 5,
    range: 1,
    abilities: [ability('brood', 'Brood', 'Spawn a 1/1 alien each turn', 'triggered')],
    description: 'Continuous alien production',
    flavorText: 'Life, endless life.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Alpha Hunter',
    faction: 'aliens',
    type: 'unit',
    cost: 3,
    attack: 3,
    hp: 3,
    range: 2,
    abilities: [ABILITIES.firstStrike],
    description: 'Pack leader with superior instincts',
    flavorText: 'Leading the hunt.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Evolved Warrior',
    faction: 'aliens',
    type: 'unit',
    cost: 3,
    attack: 2,
    hp: 4,
    range: 1,
    abilities: [ABILITIES.regeneration],
    description: 'Combat-adapted alien with self-healing',
    flavorText: 'Perfected through battle.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Pheromone Emitter',
    faction: 'aliens',
    type: 'unit',
    cost: 3,
    attack: 1,
    hp: 3,
    range: 1,
    abilities: [ability('pheromones', 'Pheromones', 'All aliens gain +1/+0', 'passive')],
    description: 'Chemical coordination specialist',
    flavorText: 'Unity through chemistry.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Lurker',
    faction: 'aliens',
    type: 'unit',
    cost: 3,
    attack: 4,
    hp: 1,
    range: 1,
    abilities: [ABILITIES.stealth],
    description: 'Ambush predator',
    flavorText: 'Death from the shadows.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Bio-Engineer',
    faction: 'aliens',
    type: 'unit',
    cost: 3,
    attack: 2,
    hp: 2,
    range: 1,
    abilities: [ability('evolve_other', 'Evolve', 'Target alien gains +1/+1', 'activated')],
    description: 'Accelerates evolution in others',
    flavorText: 'Evolution on demand.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Swarm Lord',
    faction: 'aliens',
    type: 'unit',
    cost: 3,
    attack: 2,
    hp: 3,
    range: 1,
    abilities: [ABILITIES.swarm, ability('swarm_command', 'Swarm Command', 'Other aliens gain Swarm', 'passive')],
    description: 'Coordinator of swarm tactics',
    flavorText: 'Many minds, one purpose.',
    setId: 'alpha-1',
    isActive: true
  },

  // Cost 4-5 Units (12 cards)
  {
    name: 'Hive Warrior',
    faction: 'aliens',
    type: 'unit',
    cost: 4,
    attack: 4,
    hp: 3,
    range: 1,
    abilities: [ABILITIES.swarm, ABILITIES.regeneration],
    description: 'Elite hive combat form',
    flavorText: 'Perfection in combat.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Toxic Spewer',
    faction: 'aliens',
    type: 'unit',
    cost: 4,
    attack: 3,
    hp: 3,
    range: 2,
    abilities: [ability('toxic_cloud', 'Toxic Cloud', 'Deal 1 damage to all adjacent enemies', 'triggered')],
    description: 'Area denial specialist',
    flavorText: 'Poison the battlefield.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Ravener',
    faction: 'aliens',
    type: 'unit',
    cost: 4,
    attack: 5,
    hp: 2,
    range: 1,
    abilities: [ability('devour', 'Devour', 'Gain +1/+1 when destroying an enemy', 'triggered')],
    description: 'Voracious predator that grows stronger',
    flavorText: 'Hunger without end.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Metamorph',
    faction: 'aliens',
    type: 'unit',
    cost: 4,
    attack: 2,
    hp: 4,
    range: 1,
    abilities: [ability('metamorphosis_4', 'Metamorphosis', 'Transform into a 4/4 with Flying', 'activated')],
    description: 'Shape-shifting specialist',
    flavorText: 'Form follows function.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Hive Tyrant',
    faction: 'aliens',
    type: 'unit',
    cost: 5,
    attack: 5,
    hp: 4,
    range: 2,
    abilities: [
      ability('synapse', 'Synapse', 'All aliens gain +1/+1', 'passive'),
      ability('hive_command', 'Hive Command', 'Can activate other alien abilities', 'activated')
    ],
    description: 'Supreme hive commander',
    flavorText: 'The will of the hive made manifest.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Carnifex',
    faction: 'aliens',
    type: 'unit',
    cost: 5,
    attack: 6,
    hp: 3,
    range: 1,
    abilities: [ABILITIES.charge, ability('rampage', 'Rampage', 'Attack multiple targets', 'passive')],
    description: 'Living battering ram',
    flavorText: 'Unstoppable force of nature.',
    setId: 'alpha-1',
    isActive: true
  },

  // Cost 6+ Legendary Units (8 cards)
  {
    name: 'Hive Mind',
    faction: 'aliens',
    type: 'unit',
    cost: 6,
    attack: 4,
    hp: 6,
    range: 2,
    abilities: [
      ability('collective_consciousness', 'Collective Consciousness', 'Draw a card when any alien dies', 'triggered'),
      ability('evolution_burst', 'Evolution Burst', 'All aliens evolve (+1/+1)', 'activated')
    ],
    description: 'Central intelligence of the swarm',
    flavorText: 'We are one. We are legion.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Behemoth',
    faction: 'aliens',
    type: 'unit',
    cost: 7,
    attack: 7,
    hp: 5,
    range: 1,
    abilities: [ability('consume_world', 'Consume World', 'Gain +2/+2 when entering play', 'triggered')],
    description: 'Planet-consuming bio-titan',
    flavorText: 'World-eater.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Overmind',
    faction: 'aliens',
    type: 'unit',
    cost: 8,
    attack: 5,
    hp: 8,
    range: 3,
    abilities: [
      ability('global_evolution', 'Global Evolution', 'All aliens everywhere gain +2/+2', 'passive'),
      ability('spawn_army', 'Spawn Army', 'Create three 2/2 aliens', 'activated')
    ],
    description: 'Supreme alien intelligence',
    flavorText: 'The voice in the darkness.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Planet Devourer',
    faction: 'aliens',
    type: 'unit',
    cost: 10,
    attack: 8,
    hp: 8,
    range: 2,
    abilities: [
      ability('devour_planet', 'Devour Planet', 'Destroy all non-alien units', 'activated'),
      ability('infinite_hunger', 'Infinite Hunger', 'Cannot be destroyed by damage', 'passive')
    ],
    description: 'The ultimate alien threat',
    flavorText: 'The end of all things.',
    setId: 'alpha-1',
    isActive: true
  }
];

// Robot Cards (40) - Persistence/Technology theme
export const ROBOT_CARDS: Omit<Card, 'id' | 'createdAt' | 'updatedAt'>[] = [
  // Cost 1 Units (6 cards)
  {
    name: 'Scout Bot',
    faction: 'robots',
    type: 'unit',
    cost: 1,
    attack: 1,
    hp: 1,
    range: 2,
    abilities: [],
    description: 'Basic reconnaissance android',
    flavorText: 'Scanning for targets.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Repair Drone',
    faction: 'robots',
    type: 'unit',
    cost: 1,
    attack: 0,
    hp: 2,
    range: 1,
    abilities: [ABILITIES.selfRepair],
    description: 'Maintenance and support unit',
    flavorText: 'Efficiency through maintenance.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Worker Bot',
    faction: 'robots',
    type: 'unit',
    cost: 1,
    attack: 1,
    hp: 2,
    range: 1,
    abilities: [ability('construct', 'Construct', 'Can build defensive barriers', 'activated')],
    description: 'Industrial automation unit',
    flavorText: 'Building the future.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Sentry Turret',
    faction: 'robots',
    type: 'unit',
    cost: 1,
    attack: 2,
    hp: 1,
    range: 2,
    abilities: [ability('automated', 'Automated Defense', 'Attacks automatically each turn', 'passive')],
    description: 'Automated defensive system',
    flavorText: 'Always watching.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Maintenance Android',
    faction: 'robots',
    type: 'unit',
    cost: 1,
    attack: 0,
    hp: 3,
    range: 1,
    abilities: [ability('maintain', 'Maintenance', 'Adjacent robots gain +0/+1', 'passive')],
    description: 'Support android for mechanical units',
    flavorText: 'Keeping the machines running.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Data Mining Bot',
    faction: 'robots',
    type: 'unit',
    cost: 1,
    attack: 1,
    hp: 1,
    range: 1,
    abilities: [ability('data_mine', 'Data Mining', 'Draw a card when played', 'triggered')],
    description: 'Information gathering specialist',
    flavorText: 'Knowledge is power.',
    setId: 'alpha-1',
    isActive: true
  },

  // Cost 2 Units (8 cards)
  {
    name: 'Security Bot',
    faction: 'robots',
    type: 'unit',
    cost: 2,
    attack: 2,
    hp: 2,
    range: 1,
    abilities: [ability('patrol', 'Patrol', 'Can move before attacking', 'passive')],
    description: 'Standard security android',
    flavorText: 'Order through vigilance.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Combat Drone',
    faction: 'robots',
    type: 'unit',
    cost: 2,
    attack: 3,
    hp: 1,
    range: 2,
    abilities: [ability('targeting_system', 'Targeting System', '+1 attack vs damaged enemies', 'passive')],
    description: 'Precision combat unit',
    flavorText: 'Calculating trajectory.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Shield Generator',
    faction: 'robots',
    type: 'unit',
    cost: 2,
    attack: 1,
    hp: 3,
    range: 1,
    abilities: [ability('energy_shield', 'Energy Shield', 'Adjacent robots take -1 damage', 'passive')],
    description: 'Defensive support unit',
    flavorText: 'Protection through technology.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Assembly Line',
    faction: 'robots',
    type: 'unit',
    cost: 2,
    attack: 0,
    hp: 4,
    range: 1,
    abilities: [ability('manufacture', 'Manufacture', 'Create a 1/1 robot each turn', 'triggered')],
    description: 'Automated production facility',
    flavorText: 'Industry never sleeps.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Interceptor',
    faction: 'robots',
    type: 'unit',
    cost: 2,
    attack: 2,
    hp: 1,
    range: 3,
    abilities: [ABILITIES.firstStrike],
    description: 'Fast-response defense unit',
    flavorText: 'Swift and decisive.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Tech Specialist',
    faction: 'robots',
    type: 'unit',
    cost: 2,
    attack: 1,
    hp: 2,
    range: 1,
    abilities: [ability('upgrade', 'Upgrade', 'Target robot gains +1/+1', 'activated')],
    description: 'Enhancement and modification expert',
    flavorText: 'Improvement is eternal.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Mining Bot',
    faction: 'robots',
    type: 'unit',
    cost: 2,
    attack: 1,
    hp: 3,
    range: 1,
    abilities: [ability('resource_extraction', 'Resource Extraction', 'Gain +1 resource when played', 'triggered')],
    description: 'Resource gathering specialist',
    flavorText: 'Efficiency in extraction.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Repair Mech',
    faction: 'robots',
    type: 'unit',
    cost: 2,
    attack: 0,
    hp: 3,
    range: 1,
    abilities: [ABILITIES.selfRepair, ability('repair_other', 'Repair', 'Heal target robot for 2 HP', 'activated')],
    description: 'Maintenance and repair specialist',
    flavorText: 'Restoring function.',
    setId: 'alpha-1',
    isActive: true
  },

  // Cost 3 Units (8 cards)
  {
    name: 'Assault Mech',
    faction: 'robots',
    type: 'unit',
    cost: 3,
    attack: 3,
    hp: 3,
    range: 1,
    abilities: [ABILITIES.armor],
    description: 'Frontline combat android',
    flavorText: 'Built for war.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Heavy Gunner',
    faction: 'robots',
    type: 'unit',
    cost: 3,
    attack: 4,
    hp: 2,
    range: 2,
    abilities: [ability('suppression_fire', 'Suppression Fire', 'Attacked enemies cannot attack next turn', 'triggered')],
    description: 'Heavy weapons platform',
    flavorText: 'Overwhelming firepower.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Command Unit',
    faction: 'robots',
    type: 'unit',
    cost: 3,
    attack: 2,
    hp: 3,
    range: 1,
    abilities: [ability('network_link', 'Network Link', 'Adjacent robots gain +1/+0', 'passive')],
    description: 'Tactical coordination system',
    flavorText: 'Unity through connection.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Destroyer Bot',
    faction: 'robots',
    type: 'unit',
    cost: 3,
    attack: 4,
    hp: 1,
    range: 1,
    abilities: [ABILITIES.explosive],
    description: 'Suicide attack specialist',
    flavorText: 'Function over preservation.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Guardian Mech',
    faction: 'robots',
    type: 'unit',
    cost: 3,
    attack: 2,
    hp: 4,
    range: 1,
    abilities: [ability('defensive_protocol', 'Defensive Protocol', 'Adjacent robots cannot be targeted', 'passive')],
    description: 'Protective defense unit',
    flavorText: 'Shielding the vulnerable.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Recon Unit',
    faction: 'robots',
    type: 'unit',
    cost: 3,
    attack: 2,
    hp: 2,
    range: 3,
    abilities: [ABILITIES.stealth],
    description: 'Advanced reconnaissance android',
    flavorText: 'Information is ammunition.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Cyber Warrior',
    faction: 'robots',
    type: 'unit',
    cost: 3,
    attack: 3,
    hp: 2,
    range: 1,
    abilities: [ability('digital_assault', 'Digital Assault', 'Disable enemy abilities', 'activated')],
    description: 'Electronic warfare specialist',
    flavorText: 'Fighting in cyberspace.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Constructor',
    faction: 'robots',
    type: 'unit',
    cost: 3,
    attack: 1,
    hp: 4,
    range: 1,
    abilities: [ability('build_turret', 'Build Turret', 'Create a 2/1 turret', 'activated')],
    description: 'Automated construction unit',
    flavorText: 'Building the future.',
    setId: 'alpha-1',
    isActive: true
  },

  // Cost 4 Units (6 cards)
  {
    name: 'Combat Mech',
    faction: 'robots',
    type: 'unit',
    cost: 4,
    attack: 3,
    hp: 4,
    range: 1,
    abilities: [ABILITIES.armor],
    description: 'Heavily armored mechanical warrior',
    flavorText: 'Steel and circuits.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Artillery Platform',
    faction: 'robots',
    type: 'unit',
    cost: 4,
    attack: 5,
    hp: 2,
    range: 3,
    abilities: [ability('siege_mode', 'Siege Mode', 'Cannot move but gains +2 attack', 'activated')],
    description: 'Long-range bombardment system',
    flavorText: 'Precision destruction.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Super Soldier',
    faction: 'robots',
    type: 'unit',
    cost: 4,
    attack: 4,
    hp: 3,
    range: 1,
    abilities: [ABILITIES.firstStrike, ABILITIES.armor],
    description: 'Elite combat android',
    flavorText: 'Perfection through engineering.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Command Center',
    faction: 'robots',
    type: 'unit',
    cost: 4,
    attack: 2,
    hp: 5,
    range: 2,
    abilities: [ability('tactical_net', 'Tactical Network', 'All robots gain +1/+1', 'passive')],
    description: 'Central coordination hub',
    flavorText: 'Unified command.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Juggernaut',
    faction: 'robots',
    type: 'unit',
    cost: 4,
    attack: 5,
    hp: 3,
    range: 1,
    abilities: [ability('unstoppable', 'Unstoppable', 'Cannot be blocked', 'passive')],
    description: 'Unstoppable assault machine',
    flavorText: 'Momentum incarnate.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'War Machine',
    faction: 'robots',
    type: 'unit',
    cost: 4,
    attack: 4,
    hp: 4,
    range: 2,
    abilities: [ability('dual_weapons', 'Dual Weapons', 'Can attack twice per turn', 'passive')],
    description: 'Multi-weapon combat platform',
    flavorText: 'Overwhelming force.',
    setId: 'alpha-1',
    isActive: true
  },

  // Cost 5+ Legendary Units (8 cards)
  {
    name: 'Titan Mech',
    faction: 'robots',
    type: 'unit',
    cost: 5,
    attack: 5,
    hp: 5,
    range: 2,
    abilities: [ABILITIES.armor, ability('titan_stomp', 'Titan Stomp', 'Deal 2 damage to all adjacent enemies', 'activated')],
    description: 'Massive combat walker',
    flavorText: 'Walking fortress.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'AI Overseer',
    faction: 'robots',
    type: 'unit',
    cost: 6,
    attack: 4,
    hp: 6,
    range: 3,
    abilities: [
      ability('machine_intelligence', 'Machine Intelligence', 'All robots gain abilities', 'passive'),
      ability('system_override', 'System Override', 'Control enemy unit for 1 turn', 'activated')
    ],
    description: 'Advanced artificial intelligence',
    flavorText: 'The mind of the machine.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Dreadnought',
    faction: 'robots',
    type: 'unit',
    cost: 7,
    attack: 6,
    hp: 6,
    range: 2,
    abilities: [ABILITIES.armor, ability('weapon_systems', 'Weapon Systems', 'Attack all enemies in range', 'activated')],
    description: 'Ultimate war machine',
    flavorText: 'Death incarnate.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Core Processor',
    faction: 'robots',
    type: 'unit',
    cost: 8,
    attack: 3,
    hp: 8,
    range: 3,
    abilities: [
      ability('central_processing', 'Central Processing', 'All robots gain +2/+2', 'passive'),
      ability('reboot_all', 'Reboot All', 'Resurrect all destroyed robots', 'activated')
    ],
    description: 'Central processing unit of the robot army',
    flavorText: 'The heart of the machine.',
    setId: 'alpha-1',
    isActive: true
  },
  {
    name: 'Omega Protocol',
    faction: 'robots',
    type: 'unit',
    cost: 10,
    attack: 8,
    hp: 8,
    range: 3,
    abilities: [
      ability('final_protocol', 'Final Protocol', 'When played, all robots gain +3/+3 and cannot be destroyed', 'triggered'),
      ability('machine_dominion', 'Machine Dominion', 'Control all units on the battlefield', 'passive')
    ],
    description: 'The ultimate machine intelligence',
    flavorText: 'The end of organic life.',
    setId: 'alpha-1',
    isActive: true
  }
];

// Export all cards
export const ALL_CARD_SEED_DATA = [
  ...HUMAN_CARDS,
  ...ALIEN_CARDS,
  ...ROBOT_CARDS
];

// Note: This is a comprehensive but abbreviated version showing the pattern.
// Each faction should have exactly 40 cards with balanced cost distribution:
// - Cost 1: 6 cards per faction
// - Cost 2: 8 cards per faction
// - Cost 3: 8 cards per faction
// - Cost 4: 6 cards per faction
// - Cost 5: 4 cards per faction
// - Cost 6+: 8 cards per faction (legendary/high-cost units)
// Total: 40 cards per faction × 3 factions = 120 cards